backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: ../../static/img

site_url: https://affectionate-ride-be4308.netlify.app/

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Landing Page'
        name: 'index'
        file: 'content/pages/index.md'
        fields:
          - label: 'Template key'
            name: 'templateKey'
            widget: 'hidden'
            default: 'landingPage'
          - label: Painting 1
            name: painting01
            widget: object
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
          - label: Painting 2
            name: painting02
            widget: object
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Wall
        name: wall
        file: content/pages/wall.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: wall
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Wall
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Wall series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
