backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: ../../static/img

site_url: https://affectionate-ride-be4308.netlify.app/

collections:
  - label: Pages
    name: pages
    files:
      - label: Landing Page
        name: index
        file: content/pages/index.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: landingPage
          - label: Painting 1
            name: painting01
            widget: object
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
          - label: Painting 2
            name: painting02
            widget: object
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Italian Landscapes
        name: italianLandscapes
        file: content/pages/italian-landscapes.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: wall
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Wall
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Wall series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Little Windows
        name: littleWindows
        file: content/pages/little-windows.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: wall
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Wall
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Wall series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Wall
        name: wall
        file: content/pages/wall.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: wall
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Wall
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Wall series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Portraits
        name: portraits
        file: content/pages/portraits.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: portraits
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Portraits
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Portraits series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Hedge
        name: hedge
        file: content/pages/hedge.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: hedge
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Hedge
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Hedge series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Skin and stone
        name: skinAndStone
        file: content/pages/skinAndStone.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: skinAndStone
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Skin and stone
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: Skin and stone series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: In the morning light
        name: inTheMorningLight
        file: content/pages/inTheMorningLight.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: inTheMorningLight
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | In the morning light
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: In the morning light series (2017)
          - label: Paintings
            name: paintings
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Technique, name: technique, widget: string }
              - { label: Dimensions, name: dimensions, widget: string }
              - { label: Year, name: year, widget: string }
      - label: Bio
        name: bio
        file: content/pages/bio.md
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: bio
          - label: HTML title
            name: htmlTitle
            widget: hidden
            default: Irene Habegger | Bio
          - label: HTML description
            name: htmlDescription
            widget: hidden
            default: My biography (little) depth.
          - { label: Image (me), name: img, widget: image }
          - { label: 'Biography', name: 'body', widget: 'markdown' }
